In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/multi_touch_attribution_data.csv')

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10000
Columns: 5

In [5]:
print(df.columns.tolist())

['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion']

In [6]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [7]:
df.isnull().sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [8]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [9]:
print(df.columns.tolist())

['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion']

In [10]:
print("Unique Channels:", df['Channel'].nunique())

Unique Channels: 6

In [11]:
print("Unique Campaigns:", df['Campaign'].nunique())

Unique Campaigns: 6

In [12]:
print(df['Channel'].value_counts())

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [13]:
print(df['Campaign'].value_counts().head())

Campaign
-                     3131
New Product Launch    1416
Retargeting           1379
Brand Awareness       1378
Winter Sale           1372
Name: count, dtype: int64

In [14]:
print(df['Conversion'].value_counts())

Conversion
No     5056
Yes    4944
Name: count, dtype: int64

In [15]:
# Data Cleaning

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  object
 2   Channel     10000 non-null  object
 3   Campaign    10000 non-null  object
 4   Conversion  10000 non-null  object
dtypes: int64(1), object(4)
memory usage: 390.8+ KB

In [17]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  datetime64[ns]
 2   Channel     10000 non-null  object
 3   Campaign    10000 non-null  object
 4   Conversion  10000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 390.8+ KB

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df[df.duplicated()]

Empty DataFrame
Columns: [User ID, Timestamp, Channel, Campaign, Conversion]
Index: []

In [21]:
print(df['Channel'].unique())

['Email' 'Search Ads' 'Social Media' 'Direct Traffic' 'Referral'
 'Display Ads']

In [22]:
print(df['Campaign'].unique())

['New Product Launch' 'Winter Sale' 'Brand Awareness' '-' 'Retargeting'
 'Discount Offer']