In [75]:
import pandas as pd
import numpy as np

In [77]:
df = pd.read_csv("retail_store_inventory.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2024-01-01,101,1001,Clothing,West,176,65,79,63,350.62,10,Sunny,No,365.21,Winter
1,2024-01-01,101,1002,Electronics,North,168,78,78,70,286.91,20,Cloudy,No,266.22,Winter
2,2024-01-01,102,1001,Clothing,North,144,49,91,52,381.41,0,Cloudy,No,377.63,Winter
3,2024-01-01,102,1002,Clothing,West,129,57,86,50,457.90,15,Sunny,No,427.99,Winter
4,2024-01-01,103,1001,Clothing,South,169,45,63,46,405.47,20,Rainy,No,396.97,Winter

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                1080 non-null   object
 1   Store ID            1080 non-null   int64
 2   Product ID          1080 non-null   int64
 3   Category            1080 non-null   object
 4   Region              1080 non-null   object
 5   Inventory Level     1080 non-null   int64
 6   Units Sold          1080 non-null   int64
 7   Units Ordered       1080 non-null   int64
 8   Demand Forecast     1080 non-null   int64
 9   Price               1080 non-null   float64
 10  Discount            1080 non-null   int64
 11  Weather Condition   1080 non-null   object
 12  Holiday/Promotion   1080 non-null   object
 13  Competitor Pricing  1080 non-null   float64
 14  Seasonality         1080 non-null   object
dtypes: float64(2), int64(7), object(6)
memory usage: 126.7+ KB

In [81]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='object')

In [83]:
df.shape

(1080, 15)

In [85]:
df.describe()

,Store ID,Product ID,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
count,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000
mean,102.000000,1001.500000,179.802778,59.261111,69.837037,59.287037,367.031546,9.601852,368.086444
std,0.816875,0.500232,25.626044,11.951569,15.632578,12.803318,129.080531,6.987265,131.960488
min,101.000000,1001.000000,91.000000,25.000000,20.000000,23.000000,150.010000,0.000000,139.740000
25%,101.000000,1001.000000,161.000000,51.000000,59.000000,51.000000,257.607500,5.000000,255.615000
50%,102.000000,1001.500000,181.000000,60.000000,70.000000,59.000000,362.255000,10.000000,367.720000
75%,103.000000,1002.000000,198.000000,68.000000,81.000000,68.000000,480.922500,15.000000,479.350000
max,103.000000,1002.000000,257.000000,98.000000,114.000000,98.000000,599.710000,20.000000,655.550000

In [87]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [89]:
print(df.columns.tolist())

['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality']

In [93]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [95]:
df["Date"].dtype

dtype('<M8[ns]')

In [97]:
df = df.dropna(subset=["Date"])

In [99]:
df = df.set_index("Date")

In [101]:
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
Date,,,,,,,,,,,,,,
2024-01-01,101,1001,Clothing,West,176,65,79,63,350.62,10,Sunny,No,365.21,Winter
2024-01-01,101,1002,Electronics,North,168,78,78,70,286.91,20,Cloudy,No,266.22,Winter
2024-01-01,102,1001,Clothing,North,144,49,91,52,381.41,0,Cloudy,No,377.63,Winter
2024-01-01,102,1002,Clothing,West,129,57,86,50,457.90,15,Sunny,No,427.99,Winter
2024-01-01,103,1001,Clothing,South,169,45,63,46,405.47,20,Rainy,No,396.97,Winter

In [103]:
df = df.sort_index()

In [105]:
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
Date,,,,,,,,,,,,,,
2024-01-01,101,1001,Clothing,West,176,65,79,63,350.62,10,Sunny,No,365.21,Winter
2024-01-01,101,1002,Electronics,North,168,78,78,70,286.91,20,Cloudy,No,266.22,Winter
2024-01-01,102,1001,Clothing,North,144,49,91,52,381.41,0,Cloudy,No,377.63,Winter
2024-01-01,102,1002,Clothing,West,129,57,86,50,457.90,15,Sunny,No,427.99,Winter
2024-01-01,103,1001,Clothing,South,169,45,63,46,405.47,20,Rainy,No,396.97,Winter

In [107]:
daily_df = df.groupby(df.index).agg({
    "Inventory Level":"mean",
    "Units Sold":"sum",
    "Units Ordered":"sum",
    "Demand Forecast":"sum",
    "Price":"mean",
    "Discount":"mean",
    "Competitor Pricing":"mean"
})

In [109]:
daily_df.head()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
Date,,,,,,,
2024-01-01,161.666667,372,471,365,345.355000,13.333333,335.860000
2024-01-02,188.000000,285,424,269,387.343333,11.666667,384.681667
2024-01-03,174.500000,337,390,325,412.145000,9.166667,409.808333
2024-01-04,169.500000,378,378,378,435.063333,9.166667,441.626667
2024-01-05,191.833333,337,438,349,326.791667,5.833333,338.005000

In [111]:
full_range = pd.date_range(
    start=daily_df.index.min(),
    end=daily_df.index.max(),
    freq="D"
)

In [113]:
missing_dates = full_range.difference(daily_df.index)

print("Expected Dates :", len(full_range))
print("Available Dates :", len(daily_df.index))
print("Missing Dates :", len(missing_dates))

Expected Dates : 180
Available Dates : 180
Missing Dates : 0

In [115]:
daily_df = daily_df.reindex(full_range)

daily_df.index.name="Date"

In [117]:
daily_df.isnull().sum()

Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Competitor Pricing    0
dtype: int64

In [119]:
daily_df = daily_df.interpolate(
    method="time",
    limit_direction="both"
)

In [121]:
daily_df.isnull().sum()

Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Competitor Pricing    0
dtype: int64

In [123]:
daily_df.index.is_monotonic_increasing

True

In [125]:
type(daily_df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [127]:
daily_df.to_csv("cleaned_supply_chain_dataset.csv")

In [129]:
print("Clean dataset saved successfully.")

Clean dataset saved successfully.

In [131]:
daily_df.head()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
Date,,,,,,,
2024-01-01,161.666667,372,471,365,345.355000,13.333333,335.860000
2024-01-02,188.000000,285,424,269,387.343333,11.666667,384.681667
2024-01-03,174.500000,337,390,325,412.145000,9.166667,409.808333
2024-01-04,169.500000,378,378,378,435.063333,9.166667,441.626667
2024-01-05,191.833333,337,438,349,326.791667,5.833333,338.005000